Update random-pop-generator

diff --git a/Linux-Debiam/testing/random-pop-generator b/Linux-Debiam/testing/random-pop-generator
--- a/Linux-Debiam/testing/random-pop-generator
+++ b/Linux-Debiam/testing/random-pop-generator
@@ -15,13 +15,13 @@ while getopts i:n:r: option
 do
 case "${option}"
 in
-i) db_input=${OPTARG};;
+i) db_original=${OPTARG};;
 n) num_lines=$OPTARG;;
 r) num_repli=$OPTARG;;
 esac
 done
 
-if [ "$db_input" = "" ]; then
+if [ "$db_original" = "" ]; then
 "${g}Error, missing arguments:${y} -i | input dataset | <string>
 ${w}$USAGE"
 exit 1
@@ -43,7 +43,7 @@ echo ''
 echo "${g}---------------------------------"
 echo "Input dataset:"
 echo "---------------------------------${w}"
-echo "$db_input"
+echo "$db_original"
 echo ''
 echo "${g}---------------------------------"
 echo "Number of samples:"
@@ -56,25 +56,49 @@ echo "---------------------------------${w}"
 echo "$num_repli"
 echo "${g}---------------------------------"
 
+sed '1d' $db_original > .db_input
+cat .db_input | grep -B999 Pop > .pop
+sed -i '$ d' .pop
+num_pop=`cat .db_input | grep -B999 Pop -i | wc -l`
+pop_num=`expr $num_pop - 1`
+sed -i "1,$pop_num d" .db_input
+sed -i '/Pop/d' .db_input
+#test if .db_input have enogh samples according to $num_lines
+max_samp=`cat .db_input | wc -l`
+if [ $num_lines -gt $max_samp ]
+    then
+    echo "${y}"
+    echo "----------------------------------------------------------------------------------------------"
+    echo " ${y}Error, the maximum number of samples is${w} $max_samp${y}, change the parameter -n to a value less than ${w}$max_samp"
+    echo "${y}----------------------------------------------------------------------------------------------"
+    echo "${w}"
+    rm -rf .01.sh .temp.sh *.locus .sed.sh .pop .db_input
+    exit 1
+    else
+    echo ''
+fi
+
 echo '#!/bin/bash' > .temp.sh
 echo 'file="$1"' >> .temp.sh
-echo "shuf -r -n $num_lines $db_input > \$file" >> .temp.sh
+echo "shuf -r -n $num_lines .db_input > \$file" >> .temp.sh
 chmod +x .temp.sh
 echo "touch {1..$num_repli}.replica.txt" > .01.sh
 chmod +x .01.sh
 ./.01.sh
 for file in *.replica.txt; do ./.temp.sh "$file"; done
-num_coll=`head -n1 $db_input | grep -o " " | wc -l`
+num_coll=`head -n1 .db_input | grep -o " " | wc -l`
 sed -i "1 i Pop" *.replica.txt
-echo "touch {1..$num_coll}.locus" > .01.sh
+#echo "touch {1..$num_coll}.locus" > .01.sh
 chmod +x .01.sh
 ./.01.sh
 echo '#!/bin/bash' > .sed.sh
 echo 'file="$1"' >> .sed.sh
 echo 'sed -i "1 i $file" *.replica.txt' >> .sed.sh
 chmod +x .sed.sh
-for file in *.locus; do ./.sed.sh "$file"; done
-sed -i "1 i $db_input" *.replica.txt
-rm -rf .01.sh .temp.sh *.locus .sed.sh
+#for file in *.locus; do ./.sed.sh "$file"; done
+sed -i "1 i .db_input" *.replica.txt
 mkdir -p $num_lines 
-mv *.txt $num_lines 
+sed -i '1d' *.txt
+sed -i -e '2{x;G};1{h;r.pop' -e 'd}' *.replica.txt
+mv *.replica.txt $num_lines 
+rm -rf .01.sh .temp.sh *.locus .sed.sh .pop .db_input
